name: Go Test Coverage

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - "dev"
      - "feature/*"
      - "bugfix/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test ./... -v -coverprofile coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
